name: ios

on:
  push:

jobs:
  export:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.3.16f1-ios-1
    steps:
      - uses: actions/checkout@v3
      - run: echo "$UNITY_LICENSE" > UnityLicenseFile.ulf && unity-editor -logFile - -quit -manualLicenseFile UnityLicenseFile.ulf || true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      - run: unity-editor -buildTarget iOS -batchmode -quit -projectPath . -logFile - -executeMethod Export.IOS
      - run: ls -la build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 1
  
  ipa:
    needs: export
    runs-on: macos-12
    defaults:
      run:
        working-directory: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - run: pwd
      - run: ls -la
      - run: ls -ld /Applications/Xcode*
      - run: sudo xcode-select -s '/Applications/Xcode_13.4.1.app/Contents/Developer'
      - run: xcodebuild -version
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - run: xcodebuild -project Unity-iPhone.xcodeproj -scheme Unity-iPhone archive -archivePath archive -sdk iphoneos
      - run: xcodebuild -exportArchive -archivePath archive.xcarchive/ -exportPath dist -exportOptionsPlist ../ExportOptions.plist
