name: macos

on:
  push:
  workflow_dispatch: 

jobs:
  macos:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: xrtk/unity-setup@v7
        with:
          build-targets: iOS
      - run: echo "${{ env.UNITY_EDITOR_PATH }}"
      - run: echo -n "$UNITY_LICENSE" > UnityLicenseFile.ulf && ${{ env.UNITY_EDITOR_PATH }} -batchmode -logFile - -quit -manualLicenseFile UnityLicenseFile.ulf || true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_MACOS }}
      - run: shasum -a 256 UnityLicenseFile.ulf
      - run: sudo xcode-select -s '/Applications/Xcode_13.4.1.app/Contents/Developer'
      - run: xcodebuild -version
      - run: ${{ env.UNITY_EDITOR_PATH }} -buildTarget iOS -batchmode -quit -projectPath . -logFile - -executeMethod Export.IOS
      - run: mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles && cp -r ${{ github.workspace }}/Provisioning\ Profiles/* ~/Library/MobileDevice/Provisioning\ Profiles; ls -la ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: P@ssw0rd
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH login.keychain
      - run: xcodebuild -project Unity-iPhone.xcodeproj -scheme Unity-iPhone archive -archivePath archive -sdk iphoneos
        working-directory: build
      - run: xcodebuild -exportArchive -archivePath archive.xcarchive/ -exportPath dist -exportOptionsPlist ../ExportOptions.plist
